name: Daily Check for CAA Updates

on:
  schedule:
    - cron: '0 8 * * *'  # Runs every day at 8 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Restore previous entries cache
        uses: actions/cache@v3
        id: cache
        with:
          path: previous_entries.json
          key: previous_entries-${{ hashFiles('scraper.py') }}

      - name: Run scraper
        run: python scraper.py

      - name: Save previous entries cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: previous_entries.json
          key: previous_entries-${{ hashFiles('scraper.py') }}
